// test-api.http
// Uso la extension de vscode: Rest Client

### Obtener los primeros 5 ratings
GET http://localhost:8000/api/ratings?desde=0&hasta=4

### Obtener los ratings del 5 al 9
GET http://localhost:8000/api/ratings?desde=5&hasta=9

### Obtener el rating de un producto específico
GET http://localhost:8000/api/ratings/66fc09d24af518ec3dec96db

### Modificar el rating de un producto específico
PUT http://localhost:8000/api/ratings/66fc09d24af518ec3dec96db
Content-Type: application/json
{
  "rating": {
    "rate": 4.5,
    "count": 100
  }
}